/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnicianRouteImport } from './routes/technician'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitizenIndexRouteImport } from './routes/citizen.index'
import { Route as DocsRolesRouteImport } from './routes/docs.roles'
import { Route as DocsRealtimeRouteImport } from './routes/docs.realtime'
import { Route as DocsPwaRouteImport } from './routes/docs.pwa'
import { Route as DocsOfflineRouteImport } from './routes/docs.offline'
import { Route as CitizenReportRouteImport } from './routes/citizen.report'
import { Route as AdminTechniciansRouteImport } from './routes/admin.technicians'
import { Route as ApiPublicSendPushRouteImport } from './routes/api/public/send-push'

const TechnicianRoute = TechnicianRouteImport.update({
  id: '/technician',
  path: '/technician',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitizenRoute,
} as any)
const DocsRolesRoute = DocsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DocsRoute,
} as any)
const DocsRealtimeRoute = DocsRealtimeRouteImport.update({
  id: '/realtime',
  path: '/realtime',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPwaRoute = DocsPwaRouteImport.update({
  id: '/pwa',
  path: '/pwa',
  getParentRoute: () => DocsRoute,
} as any)
const DocsOfflineRoute = DocsOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => DocsRoute,
} as any)
const CitizenReportRoute = CitizenReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => CitizenRoute,
} as any)
const AdminTechniciansRoute = AdminTechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicSendPushRoute = ApiPublicSendPushRouteImport.update({
  id: '/api/public/send-push',
  path: '/api/public/send-push',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/citizen': typeof CitizenRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/technician': typeof TechnicianRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/citizen/report': typeof CitizenReportRoute
  '/docs/offline': typeof DocsOfflineRoute
  '/docs/pwa': typeof DocsPwaRoute
  '/docs/realtime': typeof DocsRealtimeRoute
  '/docs/roles': typeof DocsRolesRoute
  '/citizen/': typeof CitizenIndexRoute
  '/api/public/send-push': typeof ApiPublicSendPushRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRouteWithChildren
  '/technician': typeof TechnicianRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/citizen/report': typeof CitizenReportRoute
  '/docs/offline': typeof DocsOfflineRoute
  '/docs/pwa': typeof DocsPwaRoute
  '/docs/realtime': typeof DocsRealtimeRoute
  '/docs/roles': typeof DocsRolesRoute
  '/citizen': typeof CitizenIndexRoute
  '/api/public/send-push': typeof ApiPublicSendPushRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/citizen': typeof CitizenRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/technician': typeof TechnicianRoute
  '/admin/technicians': typeof AdminTechniciansRoute
  '/citizen/report': typeof CitizenReportRoute
  '/docs/offline': typeof DocsOfflineRoute
  '/docs/pwa': typeof DocsPwaRoute
  '/docs/realtime': typeof DocsRealtimeRoute
  '/docs/roles': typeof DocsRolesRoute
  '/citizen/': typeof CitizenIndexRoute
  '/api/public/send-push': typeof ApiPublicSendPushRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/citizen'
    | '/docs'
    | '/technician'
    | '/admin/technicians'
    | '/citizen/report'
    | '/docs/offline'
    | '/docs/pwa'
    | '/docs/realtime'
    | '/docs/roles'
    | '/citizen/'
    | '/api/public/send-push'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/docs'
    | '/technician'
    | '/admin/technicians'
    | '/citizen/report'
    | '/docs/offline'
    | '/docs/pwa'
    | '/docs/realtime'
    | '/docs/roles'
    | '/citizen'
    | '/api/public/send-push'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/citizen'
    | '/docs'
    | '/technician'
    | '/admin/technicians'
    | '/citizen/report'
    | '/docs/offline'
    | '/docs/pwa'
    | '/docs/realtime'
    | '/docs/roles'
    | '/citizen/'
    | '/api/public/send-push'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CitizenRoute: typeof CitizenRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  TechnicianRoute: typeof TechnicianRoute
  ApiPublicSendPushRoute: typeof ApiPublicSendPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technician': {
      id: '/technician'
      path: '/technician'
      fullPath: '/technician'
      preLoaderRoute: typeof TechnicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/docs/roles': {
      id: '/docs/roles'
      path: '/roles'
      fullPath: '/docs/roles'
      preLoaderRoute: typeof DocsRolesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/realtime': {
      id: '/docs/realtime'
      path: '/realtime'
      fullPath: '/docs/realtime'
      preLoaderRoute: typeof DocsRealtimeRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/pwa': {
      id: '/docs/pwa'
      path: '/pwa'
      fullPath: '/docs/pwa'
      preLoaderRoute: typeof DocsPwaRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/offline': {
      id: '/docs/offline'
      path: '/offline'
      fullPath: '/docs/offline'
      preLoaderRoute: typeof DocsOfflineRouteImport
      parentRoute: typeof DocsRoute
    }
    '/citizen/report': {
      id: '/citizen/report'
      path: '/report'
      fullPath: '/citizen/report'
      preLoaderRoute: typeof CitizenReportRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/admin/technicians': {
      id: '/admin/technicians'
      path: '/technicians'
      fullPath: '/admin/technicians'
      preLoaderRoute: typeof AdminTechniciansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/send-push': {
      id: '/api/public/send-push'
      path: '/api/public/send-push'
      fullPath: '/api/public/send-push'
      preLoaderRoute: typeof ApiPublicSendPushRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminTechniciansRoute: typeof AdminTechniciansRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminTechniciansRoute: AdminTechniciansRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CitizenRouteChildren {
  CitizenReportRoute: typeof CitizenReportRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
}

const CitizenRouteChildren: CitizenRouteChildren = {
  CitizenReportRoute: CitizenReportRoute,
  CitizenIndexRoute: CitizenIndexRoute,
}

const CitizenRouteWithChildren =
  CitizenRoute._addFileChildren(CitizenRouteChildren)

interface DocsRouteChildren {
  DocsOfflineRoute: typeof DocsOfflineRoute
  DocsPwaRoute: typeof DocsPwaRoute
  DocsRealtimeRoute: typeof DocsRealtimeRoute
  DocsRolesRoute: typeof DocsRolesRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsOfflineRoute: DocsOfflineRoute,
  DocsPwaRoute: DocsPwaRoute,
  DocsRealtimeRoute: DocsRealtimeRoute,
  DocsRolesRoute: DocsRolesRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CitizenRoute: CitizenRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  TechnicianRoute: TechnicianRoute,
  ApiPublicSendPushRoute: ApiPublicSendPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
